tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                    "#000615",
        "primary-container":          "#0b1f3a",
        "on-primary":                 "#ffffff",
        "on-primary-container":       "#7587a7",
        "primary-fixed":              "#d6e3ff",
        "primary-fixed-dim":          "#b5c7ea",
        "on-primary-fixed":           "#071c36",
        "on-primary-fixed-variant":   "#364764",
        "inverse-primary":            "#b5c7ea",
        "secondary":                  "#30628d",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#9fceff",
        "on-secondary-container":     "#245882",
        "secondary-fixed":            "#cfe5ff",
        "secondary-fixed-dim":        "#9ccbfc",
        "on-secondary-fixed":         "#001d33",
        "on-secondary-fixed-variant": "#104a74",
        "tertiary":                   "#0b0600",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#2a1d00",
        "on-tertiary-container":      "#a88124",
        "tertiary-fixed":             "#ffdea0",
        "tertiary-fixed-dim":         "#eec05e",
        "on-tertiary-fixed":          "#261a00",
        "on-tertiary-fixed-variant":  "#5c4300",
        "background":                 "#fcf8fb",
        "on-background":              "#1b1b1d",
        "surface":                    "#fcf8fb",
        "surface-dim":                "#dcd9dc",
        "surface-bright":             "#fcf8fb",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f6f3f5",
        "surface-container":          "#f0edef",
        "surface-container-high":     "#eae7ea",
        "surface-container-highest":  "#e4e2e4",
        "surface-variant":            "#e4e2e4",
        "surface-tint":               "#4d5f7d",
        "on-surface":                 "#1b1b1d",
        "on-surface-variant":         "#44474d",
        "outline":                    "#75777e",
        "outline-variant":            "#c4c6ce",
        "inverse-surface":            "#303032",
        "inverse-on-surface":         "#f3f0f2",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
      },
      spacing: {
        "margin-page": "48px",
        "gutter":      "24px",
        "unit":        "4px",
        "stack-sm":    "8px",
        "stack-md":    "16px",
        "stack-lg":    "32px",
        "section-gap": "80px",
      }
    }
  }
};
